# doc: https://github.com/lowlighter/metrics/blob/master/README.md#-plugins

name: Lowlighter Metrics

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  # (optional) Run workflow manually
  workflow_dispatch:
  
  # (optional) Run workflow when pushing on master/main
  push:
    branches:
      - main
      - master
  
  # Schedule daily updates
  schedule:
    - cron: '0 * * * *'
  
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

