# docs: https://github.com/gautamkrishnar/blog-post-workflow

name: Add posts from Feed to README

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  # (optional) Run workflow manually
  workflow_dispatch:
  
  # (optional) Run workflow when pushing on master/main
  push:
    branches:
      - main
      - master
  
  # Schedule daily updates
  schedule:
    - cron: '0 * * * *'

permissions:
  contents: write # To write the generated contents to the readme

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Pull posts from feed
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://dev.to/feed/t4inha"
          max_post_count: 8
